#!/usr/bin/env bash

repo_update() {
    rm -f ./gcurse_repo.db.tar.gz && rm -f ./gcurse_repo.files.tar.gz
    rm -f ./*.old && rm -f ./*.old.sig
    repo-add gcurse_repo.db.tar.gz ./*.pkg.tar.xz --quiet --remove
    rm -f ./*.old && rm -f ./*.old.sig
}

repo_commit() {
    git add -A
    MSG="repo update $(date +'%a %Y-%m-%d_%H%M%S')"
    git commit -a -m "$MSG"
    git push origin master
}

repo_update
repo_commit

echo
echo
echo "Press enter to close"
read dummy
