#!/usr/bin/env bash

repo_update() {
    rm -f ./gcurse_repo.db.tar.gz && rm -f ./gcurse_repo.files.tar.gz
    rm -f ./*.old && rm -f ./*.old.sig
    repo-add gcurse_repo.db.tar.gz ./*.pkg.tar.xz --quiet --remove
    rm -f ./*.old && rm -f ./*.old.sig
}

repo_commit() {
    git add -A
    MSG="repo update $(date +'%a %Y-%m-%d_%H%M%S')"
    git commit -a -m "$MSG"
    git push --force origin master
}

if [[ -z "$1" ]]; then
    repo_update
    repo_commit
else
    [[ "$1" == "update" ]] && repo_update
    [[ "$1" == "commit" ]] && repo_commit
fi

echo
echo
echo "Press enter to close"
read dummy
